// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlQRTFM5UrVJupHGmAuDw-DCAV9Y0e_-k',
    appId: '1:532614685544:web:52edfef6094ca37474ecdd',
    messagingSenderId: '532614685544',
    projectId: 'finanzaspractica-6adcd',
    authDomain: 'finanzaspractica-6adcd.firebaseapp.com',
    storageBucket: 'finanzaspractica-6adcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDza9kqCjIDJxbAwxtP2aH8MSnq1ESr9-4',
    appId: '1:532614685544:android:2fce176a5f400c9474ecdd',
    messagingSenderId: '532614685544',
    projectId: 'finanzaspractica-6adcd',
    storageBucket: 'finanzaspractica-6adcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHWLN9CKEywVau9Zj9C5G-ZbGFczBEZc',
    appId: '1:532614685544:ios:69721fce5decb31174ecdd',
    messagingSenderId: '532614685544',
    projectId: 'finanzaspractica-6adcd',
    storageBucket: 'finanzaspractica-6adcd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMHWLN9CKEywVau9Zj9C5G-ZbGFczBEZc',
    appId: '1:532614685544:ios:69721fce5decb31174ecdd',
    messagingSenderId: '532614685544',
    projectId: 'finanzaspractica-6adcd',
    storageBucket: 'finanzaspractica-6adcd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlQRTFM5UrVJupHGmAuDw-DCAV9Y0e_-k',
    appId: '1:532614685544:web:245baa9a28d29d4274ecdd',
    messagingSenderId: '532614685544',
    projectId: 'finanzaspractica-6adcd',
    authDomain: 'finanzaspractica-6adcd.firebaseapp.com',
    storageBucket: 'finanzaspractica-6adcd.appspot.com',
  );
}
